organization_databases:
  aircomm:                              'aircomm'
  cies:                                 'cies'
  patmos_engineering_services':         'patmos'
  airworthiness_certification_services: 'patmos'
  astronics_peco:                       'patmos'
  ball_aerospace:                       'patmos'
  cadent:                               'patmos'
  curtiss_wright:                       'patmos'
  demo:                                 'patmos'
  enviro:                               'enviro'
  iee:                                  'patmos'
  mindrum:                              'patmos'
  patmos:                               'patmos'
  safran:                               'patmos'
  test:                                 'patmos' 
