DELETE FROM action_items WHERE organization != 'demo';
DELETE FROM document_comments WHERE organization != 'demo';
DELETE FROM document_attachments WHERE organization != 'demo';
DELETE FROM test_procedures WHERE organization != 'demo';
DELETE FROM test_cases WHERE organization != 'demo';
DELETE FROM code_checkmark_hits WHERE organization != 'demo';
DELETE FROM code_checkmarks WHERE organization != 'demo';
DELETE FROM code_conditional_blocks WHERE organization != 'demo';
DELETE FROM source_codes WHERE organization != 'demo';
DELETE FROM low_level_requirements WHERE organization != 'demo';
DELETE FROM high_level_requirements WHERE organization != 'demo';
DELETE FROM documents WHERE organization != 'demo';
DELETE FROM github_accesses WHERE organization != 'demo';
DELETE FROM gitlab_accesses WHERE organization != 'demo';
DELETE FROM document_types WHERE organization != 'demo';
DELETE FROM model_files WHERE organization != 'demo';
DELETE FROM review_attachments WHERE organization != 'demo';
DELETE FROM checklist_items WHERE organization != 'demo';
DELETE FROM reviews WHERE organization != 'demo';
DELETE FROM problem_report_attachments WHERE organization != 'demo';
DELETE FROM problem_report_histories;
DELETE FROM problem_reports WHERE organization != 'demo';
DELETE FROM items WHERE organization != 'demo';
DELETE FROM system_requirements WHERE organization != 'demo';
DELETE FROM change_sessions WHERE organization != 'demo';
DELETE FROM data_changes WHERE organization != 'demo';
DELETE FROM projects WHERE organization != 'demo';
DELETE FROM archives WHERE organization != 'demo';
DELETE FROM template_checklist_items WHERE organization in ('tier1', 'cies', 'safran', 'iee', 'airworthiness_certification_services', 'patmos_engineering_services');
DELETE FROM template_checklists WHERE organization in ('tier1', 'cies', 'safran', 'iee', 'airworthiness_certification_services', 'patmos_engineering_services');
DELETE FROM template_documents WHERE organization in ('tier1', 'cies', 'safran', 'iee', 'airworthiness_certification_services', 'patmos_engineering_services');
